---
title: "IFT140 analysis for Nature Methods paper"
author: "Belinda Phipson"
date: "7 September 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction


```{r}
# Remove this line Belinda
setwd("D:/_MCRI/_Analysis projects/MelissaLittle/NatureMethods/StatisticalAnalysis")
```


```{r}
library(edgeR)
library(limma)
library(org.Hs.eg.db)
library(lme4)
library(RColorBrewer)
library(NMF)
library(RUVSeq)
library(scatterplot3d)
source("./Functions/ggplotColors.R")
source("./Functions/normCounts.R")
```



```{r}
raw <- read.csv(file="./Data/countsIFT140.txt", sep="\t",
                stringsAsFactors=FALSE,skip=1, row.names=1)
counts <- raw[,6:ncol(raw)]

targets <- read.csv("./Data/SampleSheet.csv",stringsAsFactors = FALSE)
targets
```

```{r}
dge <- DGEList(counts=counts, genes=rownames(counts), group=targets$Group)
colnames(dge) <- paste(targets$ID,targets$Group,sep=".")
ann <- select(org.Hs.eg.db, keys=rownames(dge), keytype = "SYMBOL",
columns=c("ENTREZID","SYMBOL","GENENAME"))
```

```{r}
ann <- ann[!duplicated(ann$SYMBOL),]
dge$genes <- ann[match(rownames(dge),ann$SYMBOL),]
dge$genes$LENGTH <- raw$Length[rownames(raw) %in% rownames(dge)]
dge
```

```{r}
pal = ggplotColors(length(unique(targets$Group)))
par(mfrow=c(1,2))
barplot(dge$samples$lib.size, names=targets$ID, las=2, cex.names=0.8,
ylab="Library size (cpm)", col = pal[factor(targets$Group)],
cex.axis=0.5)
plotMDS(dge, col=pal[factor(targets$Group)], gene.selection = "common",
labels=targets$ID)
legend("topright", legend=levels(factor(targets$Group)), text.col=pal)
```

```{r}
isexpr <- rowSums(cpm(dge) > 1) >= 3
y <- dge[isexpr,,keep.lib.sizes=FALSE]
y <- calcNormFactors(y)
```

```{r}
design <- model.matrix(~0+factor(targets$Group)+factor(targets$Pair))
colnames(design) <- c(levels(factor(targets$Group)),levels(factor(targets$Pair))[-1])
v <- voom(y, design, plot=TRUE)
```

```{r}
fit <- lmFit(v, design)
c.matrix <- makeContrasts(DisVsCtrl=Disease-Control,
levels=design)
fitc <- contrasts.fit(fit, c.matrix)
fit2 <- eBayes(fitc, trend=TRUE, robust=TRUE)

dt <- decideTests(fit2)
summary(dt)

top <- topTable(fit2,coef=1,n="Inf")
```

```{r}
# TREAT analysis
fit.treat <- treat(fit2,lfc=log2(1.25))
topTreat(fit.treat,coef=1)
summary(decideTests(fit.treat))
topGO(goana(fit.treat,geneid="ENTREZID",trend="LENGTH"))
```


# Add variability data

```{r}
vardata <- read.csv("D:/_MCRI/_Analysis projects/MelissaLittle/VariabilityInterIntraExp/NewData/VarCompResults_07052017.csv",stringsAsFactors=FALSE)
vardata$VarRank <- c(1:nrow(vardata))

m <- match(top$SYMBOL,vardata$Original_symbol)
top$VarRank <- vardata$VarRank[m]

max(vardata$VarRank)
top$VarRank[is.na(top$VarRank)] <- max(vardata$VarRank) 

boxplot(top$VarRank[top$adj.P.Val<0.05],top$VarRank[top$adj.P.Val>0.05],names=c("DE","Not DE"),ylab="Variability Rank",cex.axis=1.5,cex.lab=1.5)

boxplot(top$VarRank[1:100],top$VarRank[1:200],top$VarRank[1:300],top$VarRank[1:400],top$VarRank[1:500],top$VarRank[500:1000],top$VarRank[top$adj.P.Val>0.05])

```

# Gene set test of variability genes

```{r}
topvar <- vardata$Original_symbol[1:1000]
mset <- match(topvar, fit$genes$SYMBOL)
mset <- mset[!is.na(mset)]
length(mset)

barcodeplot(fit2$t[,1],mset)
title("Top 1000 most variable genes")
roast(v,index=mset,design=design,contrast=c.matrix[,1])
```

```{r}
lcpm <- normCounts(y,log=TRUE,prior.count = 1)
aheatmap(lcpm[mset,],annCol=list(Patient=targets$Group,Diff=targets$Pair),fontsize=12)
```

```{r}
par(mar=c(4.5,4.5,2,2))
par(mfrow=c(1,2))
plotMDS(y[mset,], top=length(mset),col=pal[factor(targets$Group)],pch=c(16,17,8)[factor(targets$Pair)],cex=3,cex.lab=1.5,cex.axis=1.5)
legend("topleft", legend=levels(factor(targets$Group)), fill=pal,cex=1.5)
legend("right",legend=levels(factor(targets$Pair)),pch=c(16,17,8),cex=1.5)
plotMDS(y[mset,], top=length(mset),col=pal[factor(targets$Group)],pch=c(16,17,8)[factor(targets$Pair)],cex=3,cex.lab=1.5,cex.axis=1.5,dim=c(3,4))
```


# GO and KEGG analysis of all genes

```{r}
topsig <- top[top$adj.P.Val<0.01,]
topGO(goana(de=topsig$ENTREZID,universe=top$ENTREZID,length=top$LENGTH))
topKEGG(kegga(de=topsig$ENTREZID,universe=top$ENTREZID,length=top$LENGTH))

topGO(goana(de=topsig$ENTREZID[topsig$logFC>0.7],universe=top$ENTREZID,length=top$LENGTH))
topKEGG(kegga(de=topsig$ENTREZID[topsig$logFC>0.7],universe=top$ENTREZID,length=top$LENGTH))

topGO(goana(de=topsig$ENTREZID[topsig$logFC< -0.7],universe=top$ENTREZID,length=top$LENGTH))
topKEGG(kegga(de=topsig$ENTREZID[topsig$logFC< -0.7],universe=top$ENTREZID,length=top$LENGTH))

go.b.dn <- goana(de=topsig$ENTREZID[topsig$logFC< -0.7],universe=top$ENTREZID,length=top$LENGTH)
```


```{r}
topvarsig <- top[top$VarRank<1000 & top$adj.P.Val<0.01,]
topGO(goana(de=topvarsig$ENTREZID,universe=top$ENTREZID,length=top$LENGTH))
topGO(goana(de=topvarsig$ENTREZID[topvarsig$logFC>0.7],universe=top$ENTREZID,length=top$LENGTH))
topGO(goana(de=topvarsig$ENTREZID[topvarsig$logFC< -0.7],universe=top$ENTREZID,length=top$LENGTH))

go.var <- goana(de=topvarsig$ENTREZID,universe=top$ENTREZID,length=top$LENGTH)
```

```{r}
topsig2 <- top[top$VarRank>1000 & top$adj.P.Val<0.01,]
topGO(goana(de=topsig2$ENTREZID,universe=top$ENTREZID,length=top$LENGTH))
topKEGG(kegga(de=topsig2$ENTREZID,universe=top$ENTREZID,length=top$LENGTH))

topGO(goana(de=topsig2$ENTREZID[topsig2$logFC>0.7],universe=top$ENTREZID,length=top$LENGTH))
topKEGG(kegga(de=topsig2$ENTREZID[topsig2$logFC>0.7],universe=top$ENTREZID,length=top$LENGTH))

topGO(goana(de=topsig2$ENTREZID[topsig2$logFC< -0.7],universe=top$ENTREZID,length=top$LENGTH))
topKEGG(kegga(de=topsig2$ENTREZID[topsig2$logFC< -0.7],universe=top$ENTREZID,length=top$LENGTH))

go.a.dn <- goana(de=topsig2$ENTREZID[topsig2$logFC< -0.7],universe=top$ENTREZID,length=top$LENGTH)
```


# Figure for paper
```{r}
pdf(file="D:/_MCRI/_Analysis projects/MelissaLittle/NatureMethods/FigureIFT140/GOfigure2.pdf",height = 5,width=17)
par(mfrow=c(1,3))
par(mar=c(4.5,21,1,1))
o <- order(go.var$P.DE)
o.go.var <- go.var[o,]
scores <- -log10(o.go.var$P.DE[1:20])
names(scores) <- o.go.var$Term[1:20]
ont <- o.go.var$Ont[1:20]

barplot(scores[20:1],beside=TRUE,horiz=TRUE,las=2,col=ggplotColors(3)[factor(ont[20:1])],cex.names = 1.2,xlab="-log10(P-value)",cex=1.5,cex.lab=1.5,main="Significant variable genes",cex.main=1.5)
abline(v=-log10(0.05),lty=2,col=colours()[275])
legend("bottomright",legend=levels(factor(ont)),fill=ggplotColors(3),cex=1.5)

o <- order(go.b.dn$P.DE)
o.go.b.dn <- go.b.dn[o,]
scoresb <- -log10(o.go.b.dn$P.DE[1:20])
names(scoresb) <- o.go.b.dn$Term[1:20]
ontb <- o.go.b.dn$Ont[1:20]

par(mar=c(4.5,15,1,1))
barplot(scoresb[20:1],beside=TRUE,horiz=TRUE,las=2,col=ggplotColors(3)[factor(ontb[20:1])],cex.names = 1.2,xlab="-log10(P-value)",cex=1.5,cex.lab=1.5,main="Down-regulated genes (before)",cex.main=1.5)
abline(v=-log10(0.05),lty=2,col=colours()[275])
legend("bottomright",legend=levels(factor(ontb)),fill=ggplotColors(3),cex=1.5)



o <- order(go.a.dn$P.DE)
o.go.a.dn <- go.a.dn[o,]
scoresa <- -log10(o.go.a.dn$P.DE[1:20])
names(scoresa) <- o.go.a.dn$Term[1:20]
onta <- o.go.a.dn$Ont[1:20]

par(mar=c(4.5,16,1,1))
barplot(scoresa[20:1],beside=TRUE,horiz=TRUE,las=2,col=ggplotColors(3)[factor(onta[20:1])],cex.names = 1.2,xlab="-log10(P-value)",cex=1.5,cex.lab=1.5,main="Down-regulated genes (after)",cex.main=1.5)
abline(v=-log10(0.05),lty=2,col=colours()[275])
legend("bottomright",legend=levels(factor(onta)),fill=ggplotColors(3),cex=1.5)

dev.off()
```

```{r}
# Colours
pdf(file="D:/_MCRI/_Analysis projects/MelissaLittle/NatureMethods/FigureIFT140/GOfigure2.pdf",height = 5,width=17)
par(mfrow=c(1,3))
par(mar=c(4.5,25,1,1))
var.col <- rep(ggplotColors(5)[2],20)
var.col[names(scores) %in% names(scoresb)]<-ggplotColors(5)[1]
var.col[names(scores) %in% names(scoresa)]<-ggplotColors(5)[1]

barplot(scores[20:1],beside=TRUE,horiz=TRUE,las=2,col=var.col[20:1],cex.names = 1.5,xlab="-log10(P-value)",cex=1.5,cex.lab=1.5,main="Significant variable genes",cex.main=1.8)
abline(v=-log10(0.05),lty=2,col=colours()[275])

before.col <- rep(ggplotColors(5)[4],20)
before.col[names(scoresb) %in% names(scoresa)]<-ggplotColors(5)[3]
before.col[names(scoresb) %in% names(scores)]<-ggplotColors(5)[1]


par(mar=c(4.5,18,1,1))
barplot(scoresb[20:1],beside=TRUE,horiz=TRUE,las=2,col=before.col[20:1],cex.names = 1.5,xlab="-log10(P-value)",cex=1.5,cex.lab=1.5,main="Down-reg with var genes ",cex.main=1.8)
abline(v=-log10(0.05),lty=2,col=colours()[275])

after.col <- rep(ggplotColors(5)[5],20)
after.col[names(scoresa) %in% names(scoresb)]<-ggplotColors(5)[3]
after.col[names(scoresa) %in% names(scores)]<-ggplotColors(5)[1]

par(mar=c(4.5,19,1,1))
barplot(scoresa[20:1],beside=TRUE,horiz=TRUE,las=2,col=after.col[20:1],cex.names = 1.5,xlab="-log10(P-value)",cex=1.5,cex.lab=1.5,main="Down-reg excluding var genes",cex.main=1.8)
abline(v=-log10(0.05),lty=2,col=colours()[275])
dev.off()
```

```{r}
par(mar=c(0,0,0,0))
plot(0,type='n',axes=FALSE,ann=FALSE)
legend("top",legend=c("Var GO overlap","Unique GO: var genes","Common GO: DE with & without var genes","Unique GO: DE with var genes","Unique GO: DE excluding var genes"),bty="n",fill=ggplotColors(5),horiz = F,cex=1.5)
```


```{r}
par(mar=c(2,2,3,2))
terms.var <- rownames(go.var)[go.var$P.DE<0.05]
terms.before <- rownames(go.b.dn)[go.b.dn$P.DE<0.05]
terms.after <- rownames(go.a.dn)[go.a.dn$P.DE<0.05]
all.go <- unique(c(rownames(go.var),rownames(go.b.dn),rownames(go.a.dn)))
res.go <- matrix(0,ncol=3,nrow=length(all.go))
rownames(res.go) <- all.go
colnames(res.go) <- c("VarGenes","Down-reg + var","Down-reg - var")
res.go[,1] <- all.go %in% terms.var 
res.go[,2] <- all.go %in% terms.before 
res.go[,3] <- all.go %in% terms.after 

vennDiagram(res.go)
title("Significant GO terms",cex.main=2)
```



# GO terms before and after removing variable genes

```{r}
go <- goana(fit2,geneid="ENTREZID",trend="LENGTH")
topGO(go)

topvar <- vardata$Original_symbol[1:1000]
mset <- match(topvar, fit2$genes$SYMBOL)
mset <- mset[!is.na(mset)]
length(mset)
go.1000r <- goana(fit2[-mset,],geneid="ENTREZID",trend="LENGTH")
topGO(go.1000r)

kegg.1000r <- kegga(fit2[-mset,],geneid="ENTREZID",trend="LENGTH")
topKEGG(kegg.1000r)
```


```{r}
# Before removing variable genes
t100up <- top$ENTREZID[top$logFC>0][1:479]
go.up <- goana(de=t100up,universe=fit2$genes$ENTREZID, species="Hs",covariate=fit2$genes$length)
topGO(go.up)

t100dn <- top$ENTREZID[top$logFC<0][1:642]
go.dn <- goana(de=t100dn,universe=fit2$genes$ENTREZID, species="Hs",covariate=fit2$genes$length)
topGO(go.dn)
```

```{r}
# After removing variable genes
top1000r <- top[top$VarRank>1000,]

t100upr <- top1000r$ENTREZID[top1000r$logFC>0][1:425]
go.1000.up <- goana(de=t100upr,universe=fit2$genes$ENTREZID, species="Hs",covariate=fit2$genes$length)
topGO(go.1000.up)

t100dnr <- top1000r$ENTREZID[top1000r$logFC<0][1:472]
go.1000.dn <- goana(de=t100dnr,universe=fit2$genes$ENTREZID, species="Hs",covariate=fit2$genes$length)
topGO(go.1000.dn)
```


# New MDSplot with TS data

```{r}
load("D:/_MCRI/_Analysis projects/MelissaLittle/VariabilityInterIntraExp/NewData/Robjects/C32-all-TS.rdata")
load("D:/_MCRI/_Analysis projects/MelissaLittle/VariabilityInterIntraExp/NewData/analysis/ift140data.Rdata")
m <- match(rownames(y),rownames(y.ts))
y.keep <- y[!is.na(m),]
y.ts.keep <- y.ts[m[!is.na(m)],]
table(rownames(y.keep)==rownames(y.ts.keep))

counts.new <- cbind(y.ts.keep$counts,y.keep$counts)
y.new <- DGEList(counts.new)

time <- c(targets.ts$Time,rep(25,6))
geno <- rep(c("CRL1502-C32","IFT140-patient","IFT140-control"),c(18,3,3))

mycol <- c(1,ggplotColors(2))[factor(geno)]
time.plot <- c(targets.ts$Time,rep(26,6))
my.pch=c(1,2,3,4,8,6,16)[factor(time.plot)]

par(mfrow=c(1,1))
par(mar=c(4.5,4.5,2,2))
md<-plotMDS(y.new,pch=my.pch,col=mycol,cex=2.25,cex.lab=1.5,cex.axis=1.5)
md$x <- -1*md$x
plotMDS(md,pch=my.pch,col=mycol,cex=2.25,cex.lab=1.5,cex.axis=1.5)
legend("top",legend=paste("Day",levels(factor(time))),pch=c(1,2,3,4,8,6),cex=1.35)
legend("bottomleft",legend=levels(factor(geno)),fill=c(1,ggplotColors(2)),cex=1.2)


```


